/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'davidde' at '7/8/16 10:46 PM' with Gradle 2.14
 *
 * @author davidde, @date 7/8/16 10:46 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
