/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'davidde' at '7/8/16 9:58 PM' with Gradle 2.14
 *
 * @author davidde, @date 7/8/16 9:58 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
